### ISSUE TITLE
Capitalize SIMIO in line 21 of simio_ms2ascii.py

### ISSUE THREAD

**Issue by adeleplunkett** [nicokurtovic/SIMIO#1]
Running the code, I think I found a simple typographical error (but that leads the code to crash, if following the example):
line 21 of simio_ms2ascii.py should be: if current_dir[-6:] != 'SIMIO/': (in current version, simio is in lower case)

This is an issue found when reviewing the code at https://github.com/openjournals/joss-reviews/issues/4942

**Comment by nicokurtovic** [comment]
Thank you for pointing out this error. The check was initially

**Comment by nicokurtovic** [comment]
Thank you for pointing out this error. The check was initially implemented so that SIMIO could be executed from inside a template folder. I have changed it now to a printed warning if the folder is different from 'SIMIO' with  capital letters
