### ISSUE TITLE
Please add a "statement of need" for the JOSS submission

### ISSUE THREAD

**Issue by adeleplunkett** [nicokurtovic/SIMIO#2]
For the JOSS review (https://github.com/openjournals/joss-reviews/issues/4942), please add a specific "statement of need" section. According to https://joss.readthedocs.io/en/latest/submitting.html, _A Statement of need section that clearly illustrates the research purpose of the software and places it in the context of related work._

I think that you include this implicitly in your documentation, but it can be clarified, which would help the reader for context.

**Comment by jeffjennings** [comment]
I agree, please make this its own section in the JOSS paper.

[https://github.com/openjournals/joss-reviews/issues/4942](https://github.com/openjournals/joss-reviews/issues/4942)

**Comment by nicokurtovic** [comment]
A statement of need has been included in the new version of the JOSS paper

**Comment by jeffjennings** [comment]
Great, I see it in the new version - thank you.
