### ISSUE TITLE
Update CASA reference

### ISSUE THREAD

**Issue by adeleplunkett** [nicokurtovic/SIMIO#4]
The recent reference for CASA should be https://ui.adsabs.harvard.edu/abs/2022PASP..134k4501C/abstract (in addition or in place of the ones you have listed already). See this link: https://casadocs.readthedocs.io/en/latest/notebooks/citing-casa.html  

https://github.com/openjournals/joss-reviews/issues/4942

**Comment by nicokurtovic** [comment]
Thank you very much for bringing this reference to my attention. I have included it in the bibliography of paper.md
