### ISSUE TITLE
Link to tutorial

### ISSUE THREAD

**Issue by adeleplunkett** [nicokurtovic/SIMIO#5]
The link from the Github page to the tutorial should go directly to https://simio-continuum.readthedocs.io/en/main/tutorials/tutorial_1.html, rather than the general documentation.  (This is a minor issue.)

https://github.com/openjournals/joss-reviews/issues/4942

**Comment by nicokurtovic** [comment]
Thanks! 
The links have been updated to point directly to the mentioned content, instead of the general documentation. I have implemented this changes in all the contents and tutorials.
