### ISSUE TITLE
Add some explanation of the template file in the Example.

### ISSUE THREAD

**Issue by adeleplunkett** [nicokurtovic/SIMIO#6]
In the “Example” on README.md, it is not clear how to get the exact template file, and where to put it. I guessed, which worked, but another line could help the general user.

https://github.com/openjournals/joss-reviews/issues/4942

**Comment by nicokurtovic** [comment]
Thank you for noticing that some information was missing. I have included in the README.md further details of where to get the template, and where to put it after downloading.
