### ISSUE TITLE
Please add to "Community Guidelines" for your software

### ISSUE THREAD

**Issue by adeleplunkett** [nicokurtovic/SIMIO#7]
For the JOSS review, please clarify this guideline:

**Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

https://github.com/openjournals/joss-reviews/issues/4942

**Comment by jeffjennings** [comment]
I agree, these would be really useful for code users and for those who want to contribute.

[https://github.com/openjournals/joss-reviews/issues/4942](https://github.com/openjournals/joss-reviews/issues/4942)

**Comment by jeffjennings** [comment]
I see the added short guidelines in the [docs](https://simio-continuum.readthedocs.io/index.html#document-content/community_guidelines).
