### ISSUE TITLE
In example, directory projects/SolarS_HD163296/images is already filled

### ISSUE THREAD

**Issue by adeleplunkett** [nicokurtovic/SIMIO#8]
In the example project: SolarS_HD163296.tar.gz, the directory projects/SolarS_HD163296/images is already filled.  This might be helpful, but it's not written anywhere in the example about whether the images can be overwritten.  Maybe just a few words for clarity will help.

https://github.com/openjournals/joss-reviews/issues/4942

**Comment by nicokurtovic** [comment]
I have included a note mentioning that the product images are already contained in the project folder that can be downloaded for the tutorial. I also clarified that running SIMIO will overwrite any existing image in the project.
